language: generic
services:
  - docker

script:
  - docker run -v `pwd`:/data:Z sigan/latex latexmk -pdf -pdflatex="pdflatex %O %S" main
deploy:
  provider: releases
  skip-cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file: "*.pdf"
  overwrite: true
  on:
    tags: true
